package shs.simulator;

import java.util.List;

import shs.common.MsgReportCall;
import shs.common.Tool;

public class CategoryCall extends CategoryObject implements Runnable {

	public CategoryCall(String referencedName, List<String> listObjects, int askedNumberSensors) {
		super(referencedName, listObjects, askedNumberSensors);
	}

	public void run() {
		try {
			while(true) {
				// Delay
				Thread.sleep((long) (6000 + Math.random()*10000));
				// Choice of the sensor
				int id = (int)(Math.random()*listObjects.size());
				String activeSensor = listObjects.get(id);
				System.out.println("A new report was generated by a '" + referencedName + "' sensor (ID " + listObjects.get(id) + ")");
				// Transmission of the call
				MsgReportCall update = new MsgReportCall(Integer.parseInt(activeSensor));
				Connector.contactServer(Tool.messageToJSON(update));
			}
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}

}
