package shs.simulator;

import java.util.List;

import shs.common.MsgReportRFID;
import shs.common.Tool;

public class CategoryRFID extends CategoryObject implements Runnable {

	public CategoryRFID(String referencedName, List<String> listObjects, int askedNumberCaptors) {
		super(referencedName, listObjects, askedNumberCaptors);
	}

	public void run() {
		
		try {
			while(true) {
				// Delay
				Thread.sleep((long) (6000 + Math.random()*10000));
				// Choice of the sensor
				int id = (int)(Math.random()*listObjects.size());
				String activeSensor = listObjects.get(id);
				System.out.println("A new report was generated by a '" + referencedName + "' sensor (ID " + listObjects.get(id) + ")");
				// Transmission of the call
				MsgReportRFID update = new MsgReportRFID(Integer.parseInt(activeSensor));
				Connector.contactServer(Tool.messageToJSON(update));
			}
		} catch (InterruptedException e) {
			e.printStackTrace();
		}


	}

}
